# Generated by Django 5.2.6 on 2026-06-10 10:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "blurb",
                    models.TextField(
                        blank=True, help_text="The 'why' — what the money is for."
                    ),
                ),
                (
                    "goal_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("account_holder", models.CharField(blank=True, max_length=120)),
                ("iban", models.CharField(blank=True, max_length=34)),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference donors should add, e.g. 'ICG donation + your name'.",
                        max_length=120,
                    ),
                ),
                (
                    "payment_link",
                    models.URLField(
                        blank=True,
                        help_text="Optional extra link (Revolut/PayPal/etc.).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(blank=True, max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Hide the donor's name on the public wall.",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "donated_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "logged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="donations.donationcampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-donated_on", "-created_at"],
            },
        ),
    ]
