# Generated by Django 5.2.6 on 2026-06-10 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=160)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("server", "Server / hosting"),
                            ("db", "Database"),
                            ("cup", "Drinks / snacks"),
                            ("ball", "Ball / bat / gear"),
                            ("heart", "General"),
                        ],
                        default="heart",
                        max_length=10,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("pitch", "Blue"),
                            ("sky", "Sky"),
                            ("amber", "Amber"),
                            ("emerald", "Green"),
                            ("red", "Red"),
                            ("stone", "Grey"),
                        ],
                        default="pitch",
                        max_length=10,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower shows first."
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_items",
                        to="donations.donationcampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
