# Generated by Django 5.2.6 on 2026-06-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_funditem"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_holder", models.CharField(blank=True, max_length=120)),
                ("iban", models.CharField(blank=True, max_length=34)),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference donors should add, e.g. 'ICG donation + your name'.",
                        max_length=120,
                    ),
                ),
                (
                    "payment_link",
                    models.URLField(
                        blank=True,
                        help_text="Optional extra link (Revolut/PayPal/etc.).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation settings",
                "verbose_name_plural": "Donation settings",
            },
        ),
        migrations.RemoveField(
            model_name="donationcampaign",
            name="account_holder",
        ),
        migrations.RemoveField(
            model_name="donationcampaign",
            name="iban",
        ),
        migrations.RemoveField(
            model_name="donationcampaign",
            name="payment_link",
        ),
        migrations.RemoveField(
            model_name="donationcampaign",
            name="payment_reference",
        ),
    ]
