# Generated by Django 5.2.4 on 2026-06-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donationsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('bank', 'Bank import')], default='manual', help_text='How this donation entered the system.', max_length=10),
        ),
    ]
