# Generated by Django 5.2.4 on 2026-06-12 13:32

from decimal import Decimal

from django.db import migrations, models


def seed_default_campaign(apps, schema_editor):
    """Ensure exactly one General Donations campaign exists. Idempotent so the
    migration is safe to re-run after a squash."""
    DonationCampaign = apps.get_model('donations', 'DonationCampaign')
    DonationCampaign.objects.update_or_create(
        is_default=True,
        defaults={
            'title': 'General Donations',
            'blurb': (
                "Support Indian Cricket Ghent — running costs, kit, drinks, "
                "hosting, and everything else that keeps the club going."
            ),
            'is_active': True,
            'goal_amount': Decimal('0.00'),
        },
    )


def unseed_default_campaign(apps, schema_editor):
    DonationCampaign = apps.get_model('donations', 'DonationCampaign')
    DonationCampaign.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcampaign',
            name='is_default',
            field=models.BooleanField(default=False, help_text='The General Donations catch-all bucket. ICG-matched bank transfers without a specific campaign reference land here. At most one row may have this set.'),
        ),
        migrations.AddConstraint(
            model_name='donationcampaign',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='one_default_campaign'),
        ),
        migrations.RunPython(seed_default_campaign, unseed_default_campaign),
    ]
