# Generated by Django 5.2.4 on 2026-06-15 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_reorder_general_fund_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty_iban', models.CharField(blank=True, help_text="Donor's bank IBAN. Primary match key when present.", max_length=34)),
                ('counterparty_name', models.CharField(blank=True, help_text='Bank counterparty name. Fallback match when no IBAN is available.', max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['counterparty_name', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('counterparty_iban', ''), _negated=True), fields=('counterparty_iban',), name='uniq_donorlink_iban')],
            },
        ),
    ]
