# Generated by Django 5.2.6 on 2026-06-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wa_lid",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=30
            ),
        ),
    ]
