# Generated by Django 5.2.6 on 2026-06-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_wa_lid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wa_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=120
            ),
        ),
    ]
