# Generated by Django 5.1.6 on 2025-03-04 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric_users', '0006_match_attendance_confirmed_match_cost_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batting_rating',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='user',
            name='bowling_rating',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='user',
            name='fielding_rating',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
