# Generated by Django 5.2.6 on 2025-09-27 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cric", "0002_poll_vote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("duration", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=100)),
                (
                    "cost_per_person",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("attendance_confirmed", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="match",
            name="attendance_confirmed",
        ),
        migrations.RemoveField(
            model_name="match",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="match",
            name="cost_per_person",
        ),
        migrations.RemoveField(
            model_name="match",
            name="date",
        ),
        migrations.RemoveField(
            model_name="match",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="match",
            name="location",
        ),
        migrations.RemoveField(
            model_name="match",
            name="time",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="match",
        ),
        migrations.AlterField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won_matches",
                to="cric.team",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="question",
            field=models.CharField(
                default="Should this session be played?", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="captain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="captained_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="match",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="cric.session",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="cric.session",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poll",
            name="session",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll",
                to="cric.session",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("user", "session")},
        ),
        migrations.RemoveField(
            model_name="payment",
            name="match",
        ),
    ]
