# Generated by Django 5.2.6 on 2025-09-27 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cric", "0003_session_remove_match_attendance_confirmed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="catches_taken",
        ),
        migrations.RemoveField(
            model_name="player",
            name="matches_played",
        ),
        migrations.RemoveField(
            model_name="player",
            name="runs_scored",
        ),
        migrations.RemoveField(
            model_name="player",
            name="stumps_taken",
        ),
        migrations.RemoveField(
            model_name="player",
            name="wickets_taken",
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="cric.team",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="cric.match",
            ),
        ),
        migrations.CreateModel(
            name="MatchPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cric.match"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cric.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("match", "player")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendance",
            name="match_player",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="cric.matchplayer",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("match_player",)},
        ),
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matches_played", models.PositiveIntegerField(default=0)),
                ("runs_scored", models.PositiveIntegerField(default=0)),
                ("wickets_taken", models.PositiveIntegerField(default=0)),
                ("catches_taken", models.PositiveIntegerField(default=0)),
                ("stumps_taken", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="match",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="player",
        ),
    ]
