# Generated by Django 5.2.6 on 2026-04-15 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cric", "0004_sessionplayer_alter_attendance_match_player_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="runs",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="wickets",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captained_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
