# Generated by Django 5.2.6 on 2025-10-11 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cric", "0004_remove_player_catches_taken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
