# Generated by Django 5.2.6 on 2026-04-15 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cric", "0005_team_runs_team_wickets_alter_team_captain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_matches",
                to="cric.team",
            ),
        ),
    ]
