# Generated by Django 5.2.6 on 2026-05-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cric", "0007_user_phone_botevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
