# Generated by Django 5.2.12 on 2026-07-24 10:30

from django.db import migrations, models


def normalize_removed_choices(apps, schema_editor):
    response_model = apps.get_model('club', 'ClubConsultationResponse')
    response_model.objects.filter(proceed_choice='more_info').update(proceed_choice='no')
    response_model.objects.filter(volunteering_choice='maybe').update(volunteering_choice='yes')


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconsultationresponse',
            name='section_questions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(normalize_removed_choices, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='clubconsultationresponse',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='clubconsultationresponse',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='clubconsultationresponse',
            name='proceed_choice',
            field=models.CharField(choices=[('yes', 'Yes, I agree that we should start the club.'), ('no', 'No, I do not think we should start the club at this time.')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clubconsultationresponse',
            name='volunteering_choice',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20),
        ),
    ]
