# Generated by Django 5.2.12 on 2026-07-24 10:41

from django.db import migrations, models


REMOVED_FINANCE_ROLES = {
    'bank_account',
    'financial_records',
    'budgets_reports',
    'tax_admin',
}
REMOVED_ROLES = REMOVED_FINANCE_ROLES | {'secretary'}


def normalize_removed_options(apps, schema_editor):
    response_model = apps.get_model('club', 'ClubConsultationResponse')
    response_model.objects.filter(membership_preference='not_sure').update(membership_preference='annual')
    response_model.objects.filter(time_commitment='not_sure').update(time_commitment='')
    for response in response_model.objects.all():
        responsibilities = response.responsibilities or []
        if not isinstance(responsibilities, list):
            continue
        normalized = []
        needs_treasurer = any(role in REMOVED_FINANCE_ROLES for role in responsibilities)
        for role in responsibilities:
            if role in REMOVED_ROLES:
                continue
            if role not in normalized:
                normalized.append(role)
        if needs_treasurer and 'treasurer' not in normalized:
            normalized.append('treasurer')
        if normalized != responsibilities:
            response.responsibilities = normalized
            response.save(update_fields=['responsibilities'])


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_clubconsultationresponse_section_questions_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_removed_options, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='clubconsultationresponse',
            name='membership_preference',
            field=models.CharField(choices=[('annual', 'Annual membership'), ('monthly', 'Monthly membership'), ('per_game', 'Payment for each game or training session'), ('combined', 'A combination of annual and occasional membership')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clubconsultationresponse',
            name='time_commitment',
            field=models.CharField(blank=True, choices=[('weekly', 'A few hours each week'), ('monthly', 'A few hours each month'), ('specific_task', 'Only when a specific task is assigned'), ('occasional', 'Only occasionally')], max_length=20),
        ),
    ]
