# Generated by Django 5.2.12 on 2026-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_clubconsultationresponse_membership_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconsultationresponse',
            name='role_primary_responsibility',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('support_only', 'No, I can only provide support')], max_length=20),
        ),
        migrations.AddField(
            model_name='clubconsultationresponse',
            name='startup_other_task',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='clubconsultationresponse',
            name='startup_primary_responsibility',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('shared', 'I can share responsibility with another person'), ('occasional', 'I can only provide occasional help'), ('more_info', 'I need more information')], max_length=20),
        ),
        migrations.AddField(
            model_name='clubconsultationresponse',
            name='startup_tasks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
