# Generated by Django 5.2.12 on 2026-07-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_clubconsultationresponse_role_primary_responsibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubconsultationresponse',
            name='membership_preference',
            field=models.CharField(blank=True, choices=[('annual', 'Annual membership'), ('monthly', 'Monthly membership'), ('per_game', 'Payment for each game or training session'), ('combined', 'A combination of annual and occasional membership')], max_length=20),
        ),
    ]
