# Generated by Django 5.2.12 on 2026-07-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('yes', 'Saturday'), ('no', 'Sunday'), ('all', 'Both')], max_length=3),
        ),
    ]
