# Generated by Django 5.2.12 on 2026-07-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric_sessions', '0003_alter_sessionplayer_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_option_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='date_option_2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
