# Generated by Django 6.0.6 on 2026-06-24 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('whatsapp_accepted', models.BooleanField(default=False, help_text='User accepts WhatsApp is required for voting')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_version', models.CharField(default='v1', help_text='Version of terms accepted', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when consent was given', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_consent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Consent',
                'verbose_name_plural': 'User Consents',
            },
        ),
    ]
