# Generated by Django 5.2.12 on 2026-07-16 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JerseyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_person', models.CharField(choices=[('self', 'Self'), ('kid', 'Kid'), ('family', 'Family'), ('guest', 'Guest')], default='self', max_length=10)),
                ('wearer_name', models.CharField(max_length=80)),
                ('item_type', models.CharField(choices=[('collar_half', '180 GSM Collar Half Sleeve'), ('collar_full', '180 GSM Collar Full Sleeve'), ('round_half', '180 GSM Round Neck Half Sleeve'), ('round_full', '180 GSM Round Neck Full Sleeve'), ('pant', '220 GSM 4-Way Lycra Pant'), ('shorts', '220 GSM 4-Way Lycra Shorts'), ('umpire_cap', 'Umpire Cap'), ('player_cap', 'Player Cap')], max_length=20)),
                ('size', models.CharField(choices=[('20', '20'), ('22', '22'), ('24', '24'), ('26', '26'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44')], max_length=2)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('jersey_number', models.CharField(blank=True, help_text='Required for shirts. Each number can be used once.', max_length=3)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jersey_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__username', 'wearer_name', 'item_type'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('jersey_number', ''), _negated=True), fields=('jersey_number',), name='unique_jersey_number_when_set')],
            },
        ),
    ]
