# Generated by Django 5.2.12 on 2026-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jerseyorder',
            name='unique_jersey_number_when_set',
        ),
        migrations.AddField(
            model_name='jerseyorder',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('boy', 'Boy'), ('girl', 'Girl'), ('unisex', 'Unisex / not specific')], default='unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='jerseyorder',
            name='jersey_number',
            field=models.CharField(blank=True, help_text='Optional. Duplicates are allowed for family/kids.', max_length=3),
        ),
    ]
