# Generated by Django 5.2.12 on 2026-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseys', '0002_remove_jerseyorder_unique_jersey_number_when_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jerseyorder',
            name='item_type',
            field=models.CharField(choices=[('collar_half', '180 GSM Collar Half Sleeve'), ('collar_full', '180 GSM Collar Full Sleeve'), ('round_half', '180 GSM Round Neck Half Sleeve'), ('round_full', '180 GSM Round Neck Full Sleeve'), ('pant', '220 GSM 4-Way Lycra Pant'), ('shorts', '220 GSM 4-Way Lycra Shorts'), ('umpire_cap', 'Umpire Hat'), ('player_cap', 'Player Cap')], max_length=20),
        ),
    ]
