# Generated by Django 5.2.12 on 2026-07-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseys', '0003_alter_jerseyorder_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jerseyorder',
            name='item_type',
            field=models.CharField(choices=[('collar_half', '180 GSM Collar Half Sleeve'), ('collar_full', '180 GSM Collar Full Sleeve'), ('round_half', '180 GSM Round Neck Half Sleeve'), ('round_full', '180 GSM Round Neck Full Sleeve'), ('pant', '220 GSM 4-Way Lycra Pant'), ('shorts', '220 GSM 4-Way Lycra Shorts'), ('umpire_cap', 'Wide-Brim Hat'), ('player_cap', 'Player Cap')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jerseyorder',
            name='size',
            field=models.CharField(choices=[('20', '20'), ('22', '22'), ('24', '24'), ('26', '26'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('FS', 'Free size - cap/hat only')], max_length=2),
        ),
    ]
