# Generated by Django 5.2.12 on 2026-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseys', '0004_alter_jerseyorder_item_type_alter_jerseyorder_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='JerseyOrderWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jersey order window', max_length=80)),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable this to restrict member ordering to the dates below.')),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jersey order window',
                'verbose_name_plural': 'Jersey order window',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
