# Generated by Django 5.2.12 on 2026-07-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseys', '0005_jerseyorderwindow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jerseyorder',
            name='size',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
