# Generated by Django 5.2.6 on 2026-07-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jerseys", "0006_alter_jerseyorder_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="jerseyorder",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="jerseyorder",
            name="jersey_number",
            field=models.CharField(
                blank=True,
                help_text="Number printed ON the jersey. Blank = no number on the jersey.",
                max_length=3,
            ),
        ),
    ]
