# Generated by Django 5.2.4 on 2026-06-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0004_donation_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display name, e.g. 'Club N26'.", max_length=80)),
                ('provider', models.CharField(choices=[('enable_banking', 'Enable Banking'), ('csv', 'CSV upload (manual)')], default='enable_banking', max_length=20)),
                ('institution_id', models.CharField(blank=True, help_text="Provider's bank identifier, e.g. 'N26_NTSBDEB1'.", max_length=80)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('provider_session_id', models.CharField(blank=True, help_text="Provider's session/requisition ID for this consent.", max_length=128)),
                ('provider_account_id', models.CharField(blank=True, help_text="Provider's internal account ID used to fetch transactions.", max_length=128)),
                ('consent_valid_until', models.DateTimeField(blank=True, help_text='PSD2 consent expiry. Below 14 days = surface re-link banner.', null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text="Provider's stable transaction identifier. Idempotency key.", max_length=128, unique=True)),
                ('booked_on', models.DateField()),
                ('value_on', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed. Positive = credit (received).', max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('counterparty_name', models.CharField(blank=True, max_length=140)),
                ('counterparty_iban', models.CharField(blank=True, max_length=34)),
                ('remittance', models.TextField(blank=True, help_text="Free-text reference. We grep for 'ICG' here.")),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('matched', 'Matched'), ('ignored', 'Ignored'), ('review', 'Needs review')], default='new', max_length=10)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transaction', to='donations.donation')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banking.banklink')),
            ],
            options={
                'ordering': ['-booked_on', '-id'],
                'indexes': [models.Index(fields=['status'], name='banking_ban_status_b765e9_idx'), models.Index(fields=['link', 'booked_on'], name='banking_ban_link_id_d0ea9b_idx')],
            },
        ),
    ]
