# Generated by Django 5.2.6 on 2026-06-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_outboundmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessage",
            name="kind",
            field=models.CharField(
                choices=[("text", "Text"), ("poll", "Poll")],
                default="text",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="poll_options",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
