# Generated by Django 5.2.6 on 2026-06-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_outboundmessage_kind_outboundmessage_poll_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botevent",
            name="wa_message_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="outboundmessage",
            name="wa_message_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
