# Generated by Django 5.2.6 on 2026-06-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0005_retirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="innings",
            name="single_batting",
            field=models.BooleanField(default=False),
        ),
    ]
