# Generated by Django 5.2.6 on 2026-07-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0011_player_match_stat"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="scoring_ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="scoring_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
