"""
Django settings for cric_core project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
import logging
logger = logging.getLogger(__name__)
load_dotenv(override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-v@v8d$*(-5sso_wrjp(_tl7o3ao(_q98*c&0d4o3c5vbwxhbj%",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"

# Application definition

# Media (user uploads, e.g. profile avatars). When CLOUDINARY_URL is set the
# default file storage routes uploads to Cloudinary (see STORAGES below); these
# locals still back local-dev uploads and the DEBUG media route in urls.py.
CLOUDINARY_URL = os.getenv("CLOUDINARY_URL", "")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    # NOTE: cloudinary_storage / cloudinary are intentionally NOT in INSTALLED_APPS.
    # The MediaCloudinaryStorage backend works purely via STORAGES (see below) and
    # the cloudinary lib auto-configures from the CLOUDINARY_URL env var. Adding
    # cloudinary_storage here registers its own collectstatic command, which reads
    # the legacy settings.STATICFILES_STORAGE and crashes under the STORAGES dict
    # (AttributeError) — breaking the prod build. Leave them out.
    "django.contrib.staticfiles",
    'django_cleanup.apps.CleanupConfig',

    'django_tables2',
    'django_htmx',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    # 'allauth.socialaccount',

    # New multi-app structure
    "apps.accounts",
    "apps.sessions",
    "apps.matches",
    "apps.polls",
    "apps.payments",
    "apps.notifications",
    "apps.donations",
    "apps.banking",
    "apps.gdpr",
]
SITE_ID = 1

LOGIN_REDIRECT_URL = '/'
# After signup, send new users through onboarding (role picker) before home.
# The onboarding view bounces existing users straight to their profile.
ACCOUNT_SIGNUP_REDIRECT_URL = '/profile/onboarding/'

# --- Email backend ---
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
    _brevo_key = os.getenv("BREVO_API_KEY", "")
    if not _brevo_key:
        raise Exception("BREVO_API_KEY environment variable is not set")
    ANYMAIL = {"BREVO_API_KEY": _brevo_key}

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "IndCric <indiancricket.ghent@gmail.com>")

BOT_WEBHOOK_TOKEN = os.getenv("BOT_WEBHOOK_TOKEN", "")
# Separate, higher-trust token for the group-bot inbound endpoint (/api/bot/inbound/).
# That endpoint WRITES Vote rows from group messages, so it must not share the
# read-only reminder/keepalive token above. See whatsapp-group-bot.md.
BOT_INBOUND_TOKEN = os.getenv("BOT_INBOUND_TOKEN", "")
# Master switch for auto-posting club updates into the WhatsApp group. Off until
# the Node group bot is deployed, so OutboundMessage rows don't pile up undrained.
WHATSAPP_GROUP_BOT_ENABLED = os.getenv("WHATSAPP_GROUP_BOT_ENABLED", "") == "1"

# WhatsApp Cloud API
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_VERIFY_TOKEN = os.getenv("WHATSAPP_VERIFY_TOKEN", "")
# Meta App Secret — used to verify X-Hub-Signature-256 on inbound webhooks.
# Leave empty in dev; required in prod to reject forged webhook calls.
WHATSAPP_APP_SECRET = os.getenv("WHATSAPP_APP_SECRET", "")
# Leave empty to disable session reminders until Meta approves the template.
WHATSAPP_REMINDER_TEMPLATE = os.getenv("WHATSAPP_REMINDER_TEMPLATE", "")
# Approved template Meta calls 'session_rsvp_temp'. Override via env if renamed.
WHATSAPP_RSVP_TEMPLATE = os.getenv("WHATSAPP_RSVP_TEMPLATE", "session_rsvp_temp")
# Locale of approved templates. en_GB matches the IndCric WABA submission.
WHATSAPP_TEMPLATE_LANGUAGE = os.getenv("WHATSAPP_TEMPLATE_LANGUAGE", "en_GB")
# Bot's display phone number in E.164 (with or without leading '+'). Used to build
# wa.me/<number>?text=YES%20<session_id> deep links in the group share message
# so members can tap-to-RSVP, which opens a free 24h service window for replies.
WHATSAPP_BOT_NUMBER = os.getenv("WHATSAPP_BOT_NUMBER", "")
# Public base URL of the site — used in bot replies (e.g. the sign-up link sent
# to unrecognised numbers). Override per-environment via env.
SITE_URL = os.getenv("SITE_URL", "https://indcric.onrender.com")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Enable Banking (PSD2 AISP) — used by apps.banking to fetch bank transactions
# and auto-create Donation rows. ENABLE_BANKING_PRIVATE_KEY_PATH points to a
# PEM file mounted as a secret on the host; never commit the key itself.
ENABLE_BANKING_APP_ID = os.getenv("ENABLE_BANKING_APP_ID", "")
ENABLE_BANKING_PRIVATE_KEY_PATH = os.getenv("ENABLE_BANKING_PRIVATE_KEY_PATH", "")
ENABLE_BANKING_REDIRECT_URL = os.getenv(
    "ENABLE_BANKING_REDIRECT_URL",
    f"{SITE_URL.rstrip('/')}/banking/link/callback/",
)
# If True, ICG-matching transactions immediately create a Donation row. If
# False, they sit in status=review for a treasurer to one-click approve.
DONATIONS_AUTO_CREATE = os.getenv("DONATIONS_AUTO_CREATE", "True").lower() == "true"

# --- allauth account behavior ---
# username/email required-ness is expressed via the `*` suffixes in
# ACCOUNT_SIGNUP_FIELDS below; the legacy ACCOUNT_EMAIL_REQUIRED /
# ACCOUNT_USERNAME_REQUIRED booleans are deprecated and dropped.
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["username*", "email*", "password1*", "password2*"]
# Custom signup form adds the required WhatsApp phone field (used by the
# WhatsApp bot integration in apps/notifications).
ACCOUNT_FORMS = {"signup": "apps.accounts.forms.CustomSignupForm"}
ACCOUNT_ADAPTER = "apps.accounts.adapter.CustomAccountAdapter"
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http" if DEBUG else "https"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[IndCric] "

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add this line after SecurityMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",  # Ensure this line is present
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'allauth.account.middleware.AccountMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = "cric_core.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates", BASE_DIR / "cric" / "templates"],  # include custom + legacy cric templates
        'APP_DIRS': True,  # ensures app templates (like cric_manage) are detected
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.notifications.context_processors.activity_unread",
                "apps.gdpr.context_processors.gdpr_context",
            ],
        },
    },
]

WSGI_APPLICATION = "cric_core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if not DEBUG and not os.getenv("CUSTOMCONNSTR_POSTGRESQL_CONNECTION_STRING"):
    required_vars = ["db_hostname", "db_databasename", "db_username", "db_password"]
    missing = [var for var in required_vars if not os.getenv(var)]
    if missing:
        raise Exception(f"Missing environment variables: {', '.join(missing)}")


# Check for connection string first (preferred method)
DATABASE_URL = os.environ.get('CUSTOMCONNSTR_POSTGRESQL_CONNECTION_STRING')

if DATABASE_URL:
    logger.info("Using connection string for database configuration")
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS'].setdefault('sslmode', 'require')
    # Render free Postgres closes idle connections; ping before reuse and reconnect if dead.
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True

# Fall back to individual environment variables if available
elif os.getenv("db_hostname") and os.getenv("db_databasename") and os.getenv("db_username") and os.getenv("db_password"):
    logger.info("Using individual environment variables for database configuration")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("db_databasename"),
            'USER': os.getenv("db_username"),
            'PASSWORD': os.getenv("db_password"),
            'HOST': os.getenv("db_hostname"),
            'PORT': os.getenv("db_port", "5432"),
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                'options': '-c search_path=django_schema,public'
            }
        }
    }
    
# Last resort: use local SQLite
else:
    logger.info("Using local SQLite database configuration")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Brussels"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Add whitenoise for efficient static file serving on Azure
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add this line after SecurityMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",  # Ensure this line is present
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'allauth.account.middleware.AccountMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

# Media files (user uploads — avatars). Served locally in DEBUG (see urls.py);
# in staging/prod the default storage is Cloudinary when CLOUDINARY_URL is set.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Storage backends. Django forbids setting both STATICFILES_STORAGE (legacy) and
# STORAGES, so pick exactly one mechanism:
#  • CLOUDINARY_URL set  → use the modern STORAGES dict: Cloudinary for uploaded
#    media, Whitenoise (manifest, compressed) for static. Drop the legacy line.
#  • CLOUDINARY_URL unset → keep the existing legacy STATICFILES_STORAGE
#    (local FileSystemStorage default for media + Whitenoise for static) exactly
#    as-is, so local dev and pre-creds staging keep working unchanged.
# Tests don't run collectstatic, so the hashed manifest has no entries — fall
# back to plain static storage under test so {% static %} renders don't error.
import sys as _sys
_under_test = 'test' in _sys.argv
_static_backend = (
    'django.contrib.staticfiles.storage.StaticFilesStorage'
    if _under_test
    else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
)
# Under test, never route media to Cloudinary — the dev box may not have the
# cloudinary_storage backend installed, and tests shouldn't hit a remote bucket.
# Force local FileSystemStorage regardless of CLOUDINARY_URL.
if CLOUDINARY_URL and not _under_test:
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': _static_backend,
        },
    }
else:
    STATICFILES_STORAGE = _static_backend

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'accounts.User'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # 'file': {
        #     'level': 'DEBUG',
        #     'class': 'logging.FileHandler',
        #     'filename': '/home/LogFiles/application.log',  # Azure Web App log directory
        #     'formatter': 'verbose',
        # },
    },
    'loggers': {
        'django': {
            'handlers': [
                'console',
                # 'file'
                ],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': [
                'console',
                # 'file'
            ],
            'level': 'DEBUG',
            'propagate': False,
        },
        'your_app_name': {  # Replace with your actual app name
            'handlers': [
                'console',
                # 'file'
            ],
            'level': 'DEBUG',
            'propagate': True,
        },
        'apps.gdpr': {
            'handlers': [
                'console',
                # 'file'
            ],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.accounts': {
            'handlers': [
                'console',
                # 'file'
            ],
            'level': 'INFO',
            'propagate': False,
        },
        'django.core.mail': {
            'handlers': [
                'console',
                # 'file'
            ],
            'level': 'DEBUG',
            'propagate': False,
        },
        'allauth': {
            'handlers': [
                'console',
                # 'file'
            ],
            'level': 'INFO',
            'propagate': False,
        },
    },
}